import type { Unit } from "../types";

export const FUNDAMENTALS: Unit = {
  id: "fundamentals",
  title: "Fundamentals",
  description: "Get to know the instrument: posture, hands, tuning, and how to read music for guitar.",
  lessons: [
    {
      id: "fund-anatomy",
      unitId: "fundamentals",
      kind: "video",
      title: "Anatomy of the Classical Guitar",
      subtitle: "Know your instrument",
      xp: 10,
      youtubeId: "_IiHwf5s6j0",
      tips: [
        "Learn the names: headstock, tuning pegs, nut, neck, frets, soundhole, rosette, bridge, saddle.",
        "Classical guitars use nylon strings — warmer tone, easier on the fingers than steel.",
        "Strings are numbered 1 (thinnest, high E) to 6 (thickest, low E).",
      ],
    },
    {
      id: "fund-posture",
      unitId: "fundamentals",
      kind: "video",
      title: "Sitting Position & Posture",
      subtitle: "Footstool, guitar support, alignment",
      xp: 10,
      youtubeId: "Awl6Q8Ef-RY",
      tips: [
        "Sit at the edge of an armless chair, both feet grounded, back tall but relaxed.",
        "Raise the left leg with a footstool (or use a guitar support) so the neck angles upward.",
        "The guitar should be stable without gripping it — no tension.",
      ],
    },
    {
      id: "fund-right-hand",
      unitId: "fundamentals",
      kind: "video",
      title: "Right-Hand Position & p-i-m-a",
      subtitle: "The fingers that make the sound",
      xp: 10,
      youtubeId: "UG-mcUhEcPE",
      tips: [
        "p = thumb (pulgar), i = index (indice), m = middle (medio), a = ring (anular).",
        "Keep the wrist gently arched, knuckles roughly parallel to the strings.",
        "Thumb plays the bass strings (6-4), fingers play the trebles (3-1).",
      ],
    },
    {
      id: "fund-left-hand",
      unitId: "fundamentals",
      kind: "video",
      title: "Left-Hand Position",
      subtitle: "Curved fingers, relaxed thumb",
      xp: 10,
      youtubeId: "HTjwvwCZmRo",
      tips: [
        "Thumb rests behind the neck, roughly opposite the second finger.",
        "Press just behind the fret with the fingertip, fingers curved.",
        "Keep the wrist straight and in line with the forearm.",
      ],
    },
    {
      id: "fund-tuning",
      unitId: "fundamentals",
      kind: "video",
      title: "Tuning the Guitar",
      subtitle: "By ear and with a tuner",
      xp: 10,
      youtubeId: "CcgPazQ0Xv8",
      tips: [
        "Open strings, low to high: E - A - D - G - B - E.",
        "Tune every time you pick up the guitar — your ear develops with practice.",
        "Nylon strings stretch: new strings need re-tuning often for a few days.",
      ],
    },
    {
      id: "fund-tablature",
      unitId: "fundamentals",
      kind: "reading",
      title: "How to Read Tablature",
      subtitle: "The six-line map of the fretboard",
      xp: 5,
      body: [
        "Tablature (tab) is a six-line diagram of the guitar's strings. The top line is the thinnest string (high E) and the bottom line is the thickest (low E). It looks like this:",
        "e|---0---2---3---|  B|---1---1---0---|  G|---0---2---0---|  D|---2---2---0---|  A|---3---0---2---|  E|-------0---3---|",
        "Numbers tell you which fret to press: 0 means play the string open, 3 means press the third fret. Numbers stacked vertically are played together as a chord.",
        "Read left to right, like text. Tab tells you where to put your fingers, but not the rhythm — that is why we pair it with listening to the piece or reading standard notation.",
        "This whole app's tab viewer (in Tools) uses this exact format — paste any tab there and tap the chords to see diagrams.",
      ],
    },
    {
      id: "fund-fretboard",
      unitId: "fundamentals",
      kind: "reading",
      title: "Notes on the Fretboard",
      subtitle: "Open strings & first position",
      xp: 5,
      body: [
        "The musical alphabet is A B C D E F G, then it repeats. Between most notes there is a whole step (2 frets), but B-C and E-F are half steps (1 fret).",
        "Open strings, 6th to 1st: E A D G B E. Every fret you go up raises the note by a half step: 6th string fret 1 = F, fret 3 = G, fret 5 = A.",
        "First position (frets 1-3) covers the notes used by most beginner pieces: E F G on string 6 · A B C on string 5 · D E F on string 4 · G A on string 3 · B C D on string 2 · E F G on string 1.",
        "Say the note names out loud as you play them — a few minutes a day and the fretboard becomes second nature.",
      ],
    },
    {
      id: "fund-strokes",
      unitId: "fundamentals",
      kind: "video",
      title: "Rest Stroke vs Free Stroke",
      subtitle: "Apoyando & tirando",
      xp: 10,
      youtubeId: "vVRmE4GipMc",
      tips: [
        "Rest stroke (apoyando): the finger plays through the string and rests on the next one — fuller, louder tone, great for melodies.",
        "Free stroke (tirando): the finger clears the neighboring string — used for arpeggios and chords.",
        "Practice both slowly on open strings, focusing on a warm, consistent tone.",
      ],
    },
    {
      id: "fund-reading",
      unitId: "fundamentals",
      kind: "video",
      title: "Reading Music & Rhythm",
      subtitle: "Note values and counting",
      xp: 10,
      youtubeId: "iCqysBkn_wQ",
      milestone: true,
      tips: [
        "Whole = 4 beats, half = 2, quarter = 1, eighth = 1/2. Clap rhythms before playing them.",
        "Count out loud: '1 & 2 & 3 & 4 &' — steady pulse first, speed later.",
        "Classical guitar music is written in treble clef, sounding an octave lower than written.",
      ],
    },
    {
      id: "fund-first-exercises",
      unitId: "fundamentals",
      kind: "practice",
      title: "First Exercises",
      subtitle: "Putting both hands to work",
      xp: 15,
      youtubeId: "AscIapGcJyQ",
      tips: [
        "Play each open treble string with i-m alternation, slow and even.",
        "Then walk frets 1-2-3 on each string with fingers 1-2-3, one note per finger.",
        "Slow is smooth, smooth is fast: use a metronome at 60 bpm.",
      ],
    },
  ],
};
