import type { Unit } from "../types";

export const TECHNIQUE: Unit = {
  id: "technique",
  title: "Technique & Warm-ups",
  description: "Build the daily habits of a classical guitarist: arpeggios, scales, slurs, and barre strength.",
  lessons: [
    {
      id: "tech-warmup-overview",
      unitId: "technique",
      kind: "video",
      title: "Daily Warm-up Routine",
      subtitle: "How to start every practice session",
      xp: 10,
      youtubeId: "rzLDiZ7qACw",
      tips: [
        "Warming up prevents injury and sets your tone for the whole session.",
        "A good routine touches both hands: slow arpeggios, a scale, and a few stretches.",
        "Keep it short — 5 to 10 minutes is plenty.",
      ],
    },
    {
      id: "tech-pima-arpeggios",
      unitId: "technique",
      kind: "practice",
      title: "p-i-m-a Arpeggio Patterns",
      subtitle: "Free-stroke fundamentals",
      xp: 15,
      youtubeId: "KN7CVmZb_AY",
      tips: [
        "Hold a simple E minor chord and cycle p-i-m-a on strings 6-3-2-1.",
        "Then reverse: p-a-m-i. Keep every note equal in volume.",
        "Plant the thumb before it plays — stability comes from preparation.",
      ],
    },
    {
      id: "tech-thumb",
      unitId: "technique",
      kind: "practice",
      title: "Thumb Independence",
      subtitle: "p vs i-m-a",
      xp: 15,
      youtubeId: "",
      tips: [
        "Alternate a bass note (p) with a treble chord (i-m-a together): p, ima, p, ima.",
        "Practice moving p between strings 6, 5 and 4 without looking.",
        "The thumb moves from its base joint — keep the tip relaxed.",
      ],
    },
    {
      id: "tech-im-alternation",
      unitId: "technique",
      kind: "practice",
      title: "i-m Alternation & String Crossing",
      subtitle: "The walking fingers",
      xp: 15,
      youtubeId: "",
      tips: [
        "Alternate i-m on one string, then cross to the next string mid-pattern.",
        "Never repeat the same finger twice — strict alternation builds speed.",
        "Try rest stroke on melodies, free stroke inside arpeggios.",
      ],
    },
    {
      id: "tech-c-major-scale",
      unitId: "technique",
      kind: "practice",
      title: "C Major Scale, First Position",
      subtitle: "Your first full scale",
      xp: 15,
      youtubeId: "Wk-jNRS0pQQ",
      tips: [
        "Two octaves in first position: start on string 5 fret 3 (C).",
        "Use i-m alternation with rest stroke, one clean note at a time.",
        "Metronome at 60 bpm, quarter notes — then eighths when perfect.",
      ],
    },
    {
      id: "tech-spider",
      unitId: "technique",
      kind: "practice",
      title: "Chromatic 1-2-3-4 Spider",
      subtitle: "Finger independence drill",
      xp: 15,
      youtubeId: "F4-YXbENQ_c",
      tips: [
        "Play frets 1-2-3-4 with fingers 1-2-3-4 on every string, up and back down.",
        "Keep fingers hovering close to the strings — no flying fingers.",
        "Move the whole pattern up a fret each day for variety.",
      ],
    },
    {
      id: "tech-slurs",
      unitId: "technique",
      kind: "video",
      title: "Slurs: Hammer-ons & Pull-offs",
      subtitle: "Legato with the left hand",
      xp: 10,
      youtubeId: "GhsEPksoygA",
      tips: [
        "Hammer-on: snap the finger down just behind the fret — speed, not force.",
        "Pull-off: the finger plucks the string sideways as it leaves.",
        "Slur pairs 1-2, 1-3, 1-4 on each string are a classic daily drill.",
      ],
    },
    {
      id: "tech-barre",
      unitId: "technique",
      kind: "video",
      title: "Barre Preparation",
      subtitle: "The technique behind Romanza & Capricho Árabe",
      xp: 10,
      youtubeId: "uvGr-TTYeEw",
      tips: [
        "Precision beats pressure: place the index right behind the fret.",
        "Roll the index slightly onto its bony edge for a harder surface.",
        "Practice partial barres (2-3 strings) before full six-string barres.",
      ],
    },
    {
      id: "tech-giuliani",
      unitId: "technique",
      kind: "practice",
      title: "Giuliani's 120 Right-Hand Studies",
      subtitle: "Mauro Giuliani, Op. 1",
      xp: 15,
      youtubeId: "XBhg_ox4pGo",
      milestone: true,
      tips: [
        "The most famous right-hand arpeggio collection ever written — just C and G7 chords.",
        "Learn patterns 1-10 first; a few minutes daily beats an hour weekly.",
        "Try both prepared (planted) and unprepared attacks.",
      ],
    },
  ],
};
